version: "3"
name: secure-password
services:
  postgres:
    image: postgres:14.5
    container_name: "postgresql"      
    environment:
      POSTGRES_DB: secure_password
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Sao_Paulo
    volumes:
      - ./db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432  
    networks:
      - postgres-secure-password-network

#  apache:
#    image: 'php:8.1-rc-apache'
#    container_name: apache
#    restart: always
#    ports:
#      - '80:80'
#    volumes:
#      - ./secure-password-app:/var/www/html
#    depends_on:
#      - pgadmin
#    links:
#      - pgadmin      

  apache:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: apache
    restart: always
    ports:
      - '80:80'
    #volumes:
    #  - ./secure-password-app:/var/www/html
    depends_on:
      - pgadmin
    links:
      - pgadmin      

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin4"  
    restart: always
    tty: false
    stdin_open: false
    environment:
      PGADMIN_DEFAULT_EMAIL: "desenvolvimento@kosmoscience.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./pgpass:/pgpass
    depends_on:
      - postgres
    networks:
      - postgres-secure-password-network

volumes:
  db_volume:
    external: true      

networks: 
  postgres-secure-password-network:
    driver: bridge
