version: "3"
name: secure-password
services:
  postgres:
    container_name: "postgresql"      
    image: postgres:14.5
    environment:
      POSTGRES_DB: secure_password
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Sao_Paulo
    volumes:
      - ./db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432  
    networks:
      - postgres-secure-password-network

  pgadmin:
    container_name: "pgadmin4"  
    image: dpage/pgadmin4
    restart: always
    tty: false
    stdin_open: false
    environment:
      PGADMIN_DEFAULT_EMAIL: "desenvolvimento@kosmoscience.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./pgpass:/pgpass
    depends_on:
      - postgres
    networks:
      - postgres-secure-password-network

  apache:
    container_name: phpapache
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
    depends_on:
      - pgadmin
    links:
      - pgadmin      

volumes:
  db_volume:
    external: true      

networks: 
  postgres-secure-password-network:
    driver: bridge
